### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by ugilio** [jjk-jacky/statusnotifier#14]
Hello,

maybe this is a strange request, but I am asking if you might consider relicensing statusnotifier under LGPLv2.1, which is compatible with GPLv2 and GPLv3.
The reason I am asking is this:
https://github.com/Alexey-Yakovenko/deadbeef/pull/1243

Basically, I'd like to use statusnotifier in a GPLv2 application (deadbeef), which is incompatible with GPLv3 (according to GNU: http://www.gnu.org/licenses/license-list.html). LGPLv2.1 should cause no problems for existing GPLv3 software using it, while allowing GPLv2 software to use it too.

Regards,
Giulio

**Comment by jjk-jacky** [comment]
Hi Giulio,

On 08/12/15 11:27, Giulio Bernardi wrote:
> Hello,
> 
> maybe this is a strange request, but I am asking if you might consider relicensing statusnotifier under LGPLv2.1, which is compatible with GPLv2 and GPLv3.
> The reason I am asking is this:
> https://github.com/Alexey-Yakovenko/deadbeef/pull/1243
> 
> Basically, I'd like to use statusnotifier in a GPLv2 application (deadbeef), which is incompatible with GPLv3 (according to GNU: http://www.gnu.org/licenses/license-list.html). LGPLv2.1 should cause no problems for existing GPLv3 software using it, while allowing GPLv2 software to use it too.

As I just said to Alexey, or mentioned here[1], I'm not really looking
to release it under LGPL or such, no.
So "gtkui" plugin seems to be GPL2+, and I somehow thought the main app
was released under zlib, but if it is under GPL2 only then that would
indeed be an issue.

Cheers,
-j

> 
> Regards,
> Giulio
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jjk-jacky/statusnotifier/issues/14
> 


[1] https://github.com/jjk-jacky/statusnotifier/issues/1
