### ISSUE TITLE
Interested in using Meson build system?

### ISSUE THREAD

**Issue by TingPing** [jjk-jacky/statusnotifier#16]
A lot of GNOME projects are moving to Meson and it is a far more simple and enjoyable build system to use. Would you be interested in me adding support for it and *ideally* dropping autotools? Since this isn't widely deployed I think it shouldn't be overly disruptive. This also helps projects that want to us this as a submodule until the point where it is widely packaged.

**Comment by jjk-jacky** [comment]
Well, I've seen projects moving to meson yes, but I'm not sure how
adding (make) dependencies such as python is (always) a good thing.
Though I guess maybe when you're building a DE you already need
it/don't care.

Either way, I'm definitely not for dropping autotools.

And considering I don't know much python & next to nothing about meson,
I'm worried about the maintenance burden of having both build systems
supported side by side...

**Comment by TingPing** [comment]
> Well, I've seen projects moving to meson yes, but I'm not sure how
adding (make) dependencies such as python is (always) a good thing.
Though I guess maybe when you're building a DE you already need
it/don't care.

Gtk and GLib both use Meson now (though optional until Gtk4) so it is very likely that by the point you build `statusnotifier` meson is already installed. For end users I don't think it is a problem.

> And considering I don't know much python & next to nothing about meson,
I'm worried about the maintenance burden of having both build systems
supported side by side...

Worth noting Meson build scripts *are not Python* so that knowledge isn't needed. Meson itself is very simple and this entire project will probably be about 100 lines worth. Unless you do something crazy I wouldn't expect a ton of maintenance.

**Comment by jjk-jacky** [comment]
> Gtk and GLib both use Meson now (though optional until Gtk4) so it is
> very likely that by the point you build `statusnotifier` meson is
> already installed. For end users I don't think it is a problem.

I don't know, I imagine there could be lots of people building app
linking GLib/GTK w/out building either themselves... those are quite
different things.

> Worth noting Meson build scripts *are not Python* so that knowledge
> isn't needed. Meson itself is very simple and this entire project
> will probably be about 100 lines worth. Unless you do something crazy
> I wouldn't expect a ton of maintenance.
 
But having to maintain 2 build systems is more work. And sure, today it
might seem that things be somewhat easy w/ meson, but who knows what
tomorrow will bring?
