### ISSUE TITLE
Python bindings?

### ISSUE THREAD

**Issue by ghost** [jjk-jacky/statusnotifier#17]
Hi.
Are python bindings planned? Auto generated bindings would probably be ok.

**Comment by jjk-jacky** [comment]
Not really no, mostly cause I don't know Python, or have no
idea what would be needed beside the supported introspection.

(Though, while I don't have much time these days, if someone was
interrested in doing it, it'd probably fall under the "patches welcome"
banner...)

**Comment by gnidorah** [comment]
@jjk-jacky Ok, thanks! BTW if your library works only under Plasma? If I start `sn-example` under i3 or Gnome I get `Failed to create status notifier: No Watcher found`

**Comment by jjk-jacky** [comment]
Of course not, but obviously you need an application providing the
StatusNotifierWatcher, i.e. the app that shows the icons (of
StatusNotifierItems) to the user and handle user interactions.

Plasma provides one, but I'm sure there are others, including some you
could run under i3 or gnome.
