### ISSUE TITLE
Syntax error in autogen.sh

### ISSUE THREAD

**Issue by xubincs** [jjk-jacky/statusnotifier#4]
autogen.sh declares functions using the 'function' which is a bash builtin, so a bin/sh shebang results a syntax error on Ubuntu which provides dash as the /bin/sh, since dash doesn't support the 'function' builtin. Removing the 'function' word would be ok.

**Comment by jjk-jacky** [comment]
woops.. yes, you're right. I see you've made a fix for it, feel free to send a pull request and I'll merge it.
